services:
  kg:
    image: kenningai/mcp-neo4j-biomechanisms:0.3.0
    ports:
      - "8002:8000"
    environment:
      NEO4J_URI: "bolt://host.docker.internal:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "${NEO4J_BIOMECHANISMS_PASSWORD}"
      NEO4J_DATABASE: "bna"
      NEO4J_TRANSPORT: "http"
      NEO4J_TELEMETRY: "false"
      NEO4J_MCP_SERVER_HOST: "0.0.0.0"
      NEO4J_MCP_SERVER_PORT: "8000"
      NEO4J_MCP_SERVER_PATH: "/api/mcp/"
      NEO4J_MCP_SERVER_ALLOWED_HOSTS: "*"
    restart: unless-stopped
  neo4j:
    image: mcp/neo4j-cypher:latest
    ports:
      - "8004:8000"
    environment:
      NEO4J_URI: "bolt://host.docker.internal:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "${NEO4J_BIOMECHANISMS_PASSWORD}"
      NEO4J_DATABASE: "neo4j"
      NEO4J_TRANSPORT: "http"
      NEO4J_TELEMETRY: "false"
      NEO4J_MCP_SERVER_HOST: "0.0.0.0"
      NEO4J_MCP_SERVER_PORT: "8000"
      NEO4J_MCP_SERVER_PATH: "/api/mcp/"
      NEO4J_MCP_SERVER_ALLOWED_HOSTS: "*"
    restart: unless-stopped
